-- #1
SELECT  DISTINCT h.HOSPITAL_NAME, NO_COMPLETED_SURVEYS
FROM    FACT_PATIENT_SURVEY ps
JOIN    DIM_HOSPITAL h
ON      ps.hospital_key = h.hospital_key
WHERE   NO_COMPLETED_SURVEYS IS NOT NULL
ORDER BY NO_COMPLETED_SURVEYS DESC;

-- #2
SELECT  h.PROVIDER_ID, h.HOSPITAL_NAME as HOSPITAL, m.MEASURE_CODE, ps.SURVEY_RESPONSE_RATE_PERCENT
FROM    FACT_PATIENT_SURVEY ps
JOIN    DIM_HOSPITAL h
ON      ps.hospital_key = h.hospital_key
JOIN    DIM_MEASURE m
ON      ps.measure_key = m.measure_key
ORDER BY 1, 2, 3;

-- #3
SELECT  COUNTY, MAX(SURVEY_RESPONSE_RATE_PERCENT)
FROM    FACT_PATIENT_SURVEY ps
JOIN    DIM_HOSPITAL h
ON      ps.hospital_key = h.hospital_key
WHERE   SURVEY_RESPONSE_RATE_PERCENT IS NOT NULL
GROUP BY COUNTY
ORDER BY 2 DESC
LIMIT 3;

-- #4
SELECT  PROVIDER_ID, HOSPITAL_NAME, MAX(SURVEY_RESPONSE_RATE_PERCENT)
FROM    FACT_PATIENT_SURVEY ps
JOIN    DIM_HOSPITAL h
ON      ps.hospital_key = h.hospital_key
WHERE   SURVEY_RESPONSE_RATE_PERCENT IS NOT NULL
GROUP BY PROVIDER_ID, HOSPITAL_NAME
ORDER BY 3 DESC
LIMIT 10;

-- #5
SELECT  COUNTY, CITY, HOSPITAL_NAME, AVG(PATIENT_SURVEY_STAR_RATING)
FROM    FACT_PATIENT_SURVEY ps
JOIN    DIM_HOSPITAL h
ON      ps.hospital_key = h.hospital_key
GROUP BY COUNTY, CITY, HOSPITAL_NAME;

-- #6
WITH CITY_HOSPITALS AS (
    SELECT  CITY, STATE, COUNT(DISTINCT HOSPITAL_NAME)
    FROM    DIM_HOSPITAL
    GROUP BY CITY, STATE
    HAVING COUNT(DISTINCT HOSPITAL_NAME) > 1
    ORDER BY 3 DESC
)
SELECT  h.CITY, h.STATE, h.HOSPITAL_NAME
FROM    DIM_HOSPITAL h
JOIN    CITY_HOSPITALS ch
ON      h.city = ch.city
AND     h.state = ch.state
ORDER BY 1, 2;

-- #7
SELECT
    AVG(SURVEY_RESPONSE_RATE_PERCENT) AS TOTAL_SURVEY_RESPONSE_RATE
FROM (
    SELECT DISTINCT
        HOSPITAL_KEY,
        SURVEY_RESPONSE_RATE_PERCENT
    FROM FACT_PATIENT_SURVEY
);

SELECT
    provider_id,
    measure_start_date,
    measure_end_date,
    COUNT(DISTINCT SURVEY_RESPONSE_RATE_PERCENT) cnt
FROM SURVEY_RAW --FACT_PATIENT_SURVEY --
GROUP BY
    provider_id,
    measure_start_date,
    measure_end_date
HAVING COUNT(DISTINCT SURVEY_RESPONSE_RATE_PERCENT) > 1;

SELECT
    hospital_key,
    measure_key,
    COUNT(DISTINCT NO_COMPLETED_SURVEYS) cnt
FROM FACT_PATIENT_SURVEY --
GROUP BY
    hospital_key,
    measure_key
HAVING COUNT(DISTINCT NO_COMPLETED_SURVEYS) > 1;

SELECT
    HOSPITAL_KEY,
    COUNT(DISTINCT SURVEY_RESPONSE_RATE_PERCENT)
FROM FACT_PATIENT_SURVEY
GROUP BY HOSPITAL_KEY
HAVING COUNT(DISTINCT SURVEY_RESPONSE_RATE_PERCENT) > 1;

SELECT  PROVIDER_ID, MEASURE_ID, COUNT(*)
FROM    SURVEY_RAW
GROUP BY PROVIDER_ID, MEASURE_ID
HAVING COUNT(*) > 1;

-- check PROVIDER_ID, MEASURE_CODE combination counts (check for uniqueness)
SELECT  h.PROVIDER_ID, m.MEASURE_CODE, COUNT(*)
FROM    FACT_PATIENT_SURVEY ps
JOIN    DIM_HOSPITAL h
ON      ps.hospital_key = h.hospital_key
JOIN    DIM_MEASURE m
ON      ps.measure_key = m.measure_key
GROUP BY h.PROVIDER_ID, m.MEASURE_CODE
HAVING COUNT(*) = 1;
