CREATE OR REPLACE TABLE DIM_MEASURE
(MEASURE_KEY INT AUTOINCREMENT PRIMARY KEY, MEASURE_CODE STRING, MEASURE_START_DATE DATE, MEASURE_END_DATE DATE);

COPY INTO "SNOWPARK_DEMO_DB"."PUBLIC"."DIM_MEASURE"
(MEASURE_CODE, MEASURE_START_DATE, MEASURE_END_DATE)
FROM (
    SELECT  $9, $21, $22
    FROM    '@"SNOWPARK_DEMO_DB"."PUBLIC"."SURVEY"'
)
FILE_FORMAT = (
    TYPE=CSV,
    SKIP_HEADER=1,
    FIELD_DELIMITER=',',
    TRIM_SPACE=TRUE,
    FIELD_OPTIONALLY_ENCLOSED_BY='"',
    REPLACE_INVALID_CHARACTERS=TRUE,
    DATE_FORMAT=AUTO,
    TIME_FORMAT=AUTO,
    TIMESTAMP_FORMAT=AUTO
)
ON_ERROR=ABORT_STATEMENT;
SELECT * FROM DIM_MEASURE;

CREATE OR REPLACE TABLE DIM_SURVEY
(SURVEY_KEY INT AUTOINCREMENT PRIMARY KEY, QUESTION STRING, ANSWER STRING);

COPY INTO "SNOWPARK_DEMO_DB"."PUBLIC"."DIM_SURVEY" (QUESTION, ANSWER)
FROM (
    SELECT $10, $11
    FROM '@"SNOWPARK_DEMO_DB"."PUBLIC"."SURVEY"'
)
PATTERN = '.*'
FILE_FORMAT = (
    TYPE=CSV,
    SKIP_HEADER=1,
    FIELD_DELIMITER=',',
    TRIM_SPACE=TRUE,
    FIELD_OPTIONALLY_ENCLOSED_BY='"',
    REPLACE_INVALID_CHARACTERS=TRUE
)
ON_ERROR=ABORT_STATEMENT;
SELECT * FROM DIM_SURVEY;

CREATE OR REPLACE TABLE DIM_HOSPITAL
(HOSPITAL_KEY INT AUTOINCREMENT PRIMARY KEY, PROVIDER_ID INTEGER, HOSPITAL_NAME STRING,
 ADDRESS STRING, CITY STRING, STATE STRING, ZIP_CODE STRING, COUNTY STRING); --, LOCATION STRING);

COPY INTO "SNOWPARK_DEMO_DB"."PUBLIC"."DIM_HOSPITAL" (PROVIDER_ID, HOSPITAL_NAME, ADDRESS, CITY, STATE, ZIP_CODE, COUNTY) --, LOCATION)
FROM (
    SELECT $1, $2, $3, $4, $5, $6, $7
    FROM '@"SNOWPARK_DEMO_DB"."PUBLIC"."SURVEY"'
)
PATTERN = '.*'
FILE_FORMAT = (
    TYPE=CSV,
    SKIP_HEADER=1,
    FIELD_DELIMITER=',',
    TRIM_SPACE=TRUE,
    FIELD_OPTIONALLY_ENCLOSED_BY='"',
    REPLACE_INVALID_CHARACTERS=TRUE
)
ON_ERROR=ABORT_STATEMENT;
SELECT * FROM DIM_HOSPITAL;


-- FACT TABLE
CREATE OR REPLACE TABLE FACT_PATIENT_SURVEY (HOSPITAL_KEY INTEGER, MEASURE_KEY INTEGER, SURVEY_KEY INTEGER, NO_COMPLETED_SURVEYS INTEGER, NO_COMPLETED_SURVEYS_FOOTNOTE STRING, SURVEY_RESPONSE_RATE_PERCENT INTEGER, SURVEY_RESPONSE_RATE_PERCENT_FOOTNOTE STRING, LINEAR_MEAN_VALUE INTEGER, ANSWER_PERCENT INTEGER, ANSWER_PERCENT_FOOTNOTE STRING, PATIENT_SURVEY_STAR_RATING INTEGER, PATIENT_SURVEY_STAR_RATING_FOOTNOTE STRING);

INSERT INTO FACT_PATIENT_SURVEY
(
    HOSPITAL_KEY,
    MEASURE_KEY,
    SURVEY_KEY,
    NO_COMPLETED_SURVEYS,
    NO_COMPLETED_SURVEYS_FOOTNOTE,
    SURVEY_RESPONSE_RATE_PERCENT,
    SURVEY_RESPONSE_RATE_PERCENT_FOOTNOTE,
    LINEAR_MEAN_VALUE,
    ANSWER_PERCENT,
    ANSWER_PERCENT_FOOTNOTE,
    PATIENT_SURVEY_STAR_RATING,
    PATIENT_SURVEY_STAR_RATING_FOOTNOTE
)
SELECT
    h.HOSPITAL_KEY,
    m.MEASURE_KEY,
    s.SURVEY_KEY,
    TRY_TO_NUMBER(src.NUMBER_OF_COMPLETED_SURVEYS),
    src.NUMBER_OF_COMPLETED_SURVEYS_FOOTNOTE,
    TRY_TO_NUMBER(src.SURVEY_RESPONSE_RATE_PERCENT),
    src.SURVEY_RESPONSE_RATE_PERCENT_FOOTNOTE,
    TRY_TO_NUMBER(src.LINEAR_MEAN_VALUE),
    TRY_TO_NUMBER(src.ANSWER_PERCENT),
    src.ANSWER_PERCENT_FOOTNOTE,
    TRY_TO_NUMBER(src.PATIENTSURVEY_STARRATING),
    src.PATIENTSURVEY_STARRATINGFOOTNOTE
FROM SURVEY_RAW src
JOIN DIM_HOSPITAL h
    ON src.PROVIDER_ID = h.PROVIDER_ID
JOIN DIM_MEASURE m
    ON src.MEASURE_ID = m.MEASURE_CODE
JOIN DIM_SURVEY s
    ON src.QUESTION = s.QUESTION AND src.ANSWER_DESCRIPTION = s.ANSWER;
SELECT  h.provider_id, h.hospital_name, h.address, h.city, h.state, h.zip_code, h.county,
        m.measure_code, s.question, s.answer, ps.patient_survey_star_rating, ps.patient_survey_star_rating_footnote,
        ps.answer_percent, ps.answer_percent_footnote, ps.linear_mean_value, ps.no_completed_surveys, ps.no_completed_surveys_footnote, ps.survey_response_rate_percent, ps.survey_response_rate_percent_footnote, m.measure_start_date, m.measure_end_date
FROM FACT_PATIENT_SURVEY ps, DIM_HOSPITAL h, DIM_MEASURE m, DIM_SURVEY s
WHERE   ps.hospital_key = h.hospital_key
AND     ps.measure_key = m.measure_key
AND     ps.survey_key = s.survey_key;

-- To load into one monolithic table
CREATE OR REPLACE TABLE SURVEY_RAW
(Provider_ID INTEGER, Hospital_Name STRING, Address STRING, City STRING, State STRING, ZIP_Code INTEGER, County_Name STRING, Phone_Number INTEGER,
    Measure_ID STRING, Question STRING, Answer_Description STRING,
    PatientSurvey_StarRating STRING, PatientSurvey_StarRatingFootnote STRING,
    Answer_Percent STRING, Answer_Percent_Footnote STRING,
    Linear_Mean_Value STRING,
    Number_of_Completed_Surveys STRING, Number_of_Completed_Surveys_Footnote STRING,
    Survey_Response_Rate_Percent STRING, Survey_Response_Rate_Percent_Footnote STRING,
    Measure_Start_Date DATE, Measure_End_Date DATE,
    Location STRING
);

COPY INTO SURVEY_RAW
FROM @SNOWPARK_DEMO_DB.PUBLIC.SURVEY
FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1, FIELD_OPTIONALLY_ENCLOSED_BY='"');

SELECT  PROVIDER_ID, Measure_Start_Date, Measure_End_Date
FROM    SURVEY_RAW;

TRUNCATE TABLE SURVEY_RAW;
SELECT * FROM SURVEY_RAW;

COPY INTO "SNOWPARK_DEMO_DB"."PUBLIC"."SURVEY_RAW"
FROM (
    SELECT $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23
    FROM '@"SNOWPARK_DEMO_DB"."PUBLIC"."SURVEY"'
)
PATTERN = '.*'
FILE_FORMAT = (
    TYPE=CSV,
    SKIP_HEADER=1,
    FIELD_DELIMITER=',',
    TRIM_SPACE=TRUE,
    FIELD_OPTIONALLY_ENCLOSED_BY='"',
    REPLACE_INVALID_CHARACTERS=TRUE,
    DATE_FORMAT=AUTO,
    TIME_FORMAT=AUTO,
    TIMESTAMP_FORMAT=AUTO
)
ON_ERROR=ABORT_STATEMENT;
-- For more details, see: https://docs.snowflake.com/en/sql-reference/sql/copy-into-table
TRUNCATE TABLE DIM_SURVEY;
TRUNCATE TABLE DIM_MEASURE;
TRUNCATE TABLE DIM_HOSPITAL;

INSERT INTO DIM_HOSPITAL (PROVIDER_ID, HOSPITAL_NAME, ADDRESS, CITY, STATE, ZIP_CODE, COUNTY)
SELECT DISTINCT PROVIDER_ID, HOSPITAL_NAME, ADDRESS, CITY, STATE, ZIP_CODE, COUNTY_NAME
FROM    SURVEY_RAW;

INSERT INTO DIM_SURVEY (QUESTION, ANSWER)
SELECT DISTINCT QUESTION, ANSWER_DESCRIPTION
FROM    SURVEY_RAW;

INSERT INTO DIM_MEASURE (MEASURE_CODE, MEASURE_START_DATE, MEASURE_END_DATE)
SELECT DISTINCT MEASURE_ID, MEASURE_START_DATE, MEASURE_END_DATE
FROM    SURVEY_RAW;
